---
title: "Understanding VariableNames"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Understanding VariableNames}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



## Editing the VariableNames file

The VariableNames file is critical to the success of the code when using new values defined in the csv-format parameter value files. The VariableNames file contains two important pieces of information: the mapping of the parameter name in the input parameter value file to the corresponding xml variable name, and the type of the variable in the xml file. **You must be familiar with the SORTIE xml file format** because this file contains the names that the code is using to identify what to change.  

The xml file contains many different formats for its variables. Some are simple formats with the variable and its value on the same line. Some include species, and some are further grouped. The Type column in the VariableNames file is critical to identify the format of the variable and thus the rules in the code for finding and replacing the right variable. So far, 7 different formats have been identified and coded.  

The current version of the VariableNames file is not exhaustive. It only contains those variables that were being used in the testing files. However, new variables that fit one of the 7 currently defined types should be able to be added and the code should run.  

_**Variable Types:** <span style="color: blue;">Blue text</span> is an example from the xml file (the SORTIE-generated file). <span style="color: green;">Green text</span> is an example from the VariableNames file and <span style="color: purple;">purple text</span> is the example from the parameter value file (the csv file)._  

Type 1: the parameter is on the same line and directly after the variable name:  
<span style="color: blue;">\<timesteps\>20\</timesteps\></span>   
<span style="color: green;">Timesteps,1,timesteps,</span>  
<span style="color: purple;">Timesteps,66,66,66,66</span> 


 with the following columns:#'
     col 1: input parameter name defined
     col 2: type
     col 3: name in the line being replaced in the base parameter file
     col 4: group name

 Column 2 defines the type of parameter to be replaced and these are the valid values:
     1 = basic case: variable parameter is directly after the name
     2 = basic case with species: same, but with a species name after it
     3 = behaviorlist type: but basic parameter - similar to 1
     4 = behaviorlist type: but with species - similar to 2
     5 = output files: so parameter file will have a directory name
     6 = groups with species on the previous line, e.g. for initial density
     
