---
title: "rsortie basics"
output: rmarkdown::html_vignette
date: "March 2022"
vignette: >
  %\VignetteIndexEntry{rsortie basics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`rsortie` is an R package that supports interacting with SORTIE-ND in an R environment.


## SORTIE-ND

SORTIE-ND (hereafter SORTIE) is an individual-based, spatially-explicit model of forest stand dynamics.  
<br>  

Specifically:  

* SORTIE simulates the processes of establishment, growth, and mortality of individuals, in resource-mediated (primarily light) interactions
* Trees are individuals with x-y coordinates that interact in neighbourhoods
* Complex, spatial, or aspatial silviculture experiments, including partial harvests and planting, are built into in SORTIE
* SORTIE tracks trees in space and time, meaning any metric that can be applied to individuals or stands, can be calculated from SORTIE outputs. 

Here we break down some of these key components:

### Behaviours  

SORTIE is like an "umbrella" model with many other models (or functions) within it.  

These other models (or functions) control processes, such as establishment, growth, mortality, and resource allocation. These processes are termed "behaviours".  

In other words, a behaviour is a function (or parameterized model) that describes part of the processes. They describe the shape of a response or relationship between variables (e.g., logistic growth curve as a function of tree size).  

Behaviors are the active part of a SORTIE simulation. Nothing in the model is pre-defined, default, or automatic. Everything that happens is done by a behavior, and all behaviors are under user control.  

For example, there can be a behaviour to calculate light levels, then another to determine tree growth as a result of the amount of light, and another to select trees to die if they grow too slowly. 

### Trees

The tree is the basic unit of data in the model. A model tree is a collection of attributes describing one individual, such as location, species, and size.

  
### SORTIE initiation  

Each simulation starts with initial tree and environment conditions, which are acted upon by behaviours to change the model state.  
<br>  
  
**SORTIE parameter file**  
  
Opening the SORTIE GUI does not instantly produce a usable model. A valid SORTIE parameter file is required.  

A SORTIE parameter file contains all of the behaviours (or functions) that define how a forest should establish, grow, and die. All the variables (or parameters) contained within the selected behaviours must be defined to make those functions work. 
  
Theoretically, you could construct a SORTIE parameter file based solely off literature-produced parameter values, as long as the functions are available in SORTIE. 
More often, over a series of years and many publications, parameter files are built from an abundance field data that are used to parameterize SORTIE behaviours (functions).  
  
After initial parameterization, validation, and model testing, certain parameter values may require calibration to better reflect forest stand dynamics in the place of interest. Calibration is the processes in which the predictions from a model are compared with observations and afterwards one or more parameter values are changed to produce predictions that match the observations.  
  
To initiate a SORTIE simulation, you must have a SORTIE parameter file (or build one) and populate all the parameter values required for each of the behaviours.  
<br>

Please see www.sortie-nd.org for detailed model description, including recommended minimum stand sizes and definition of all behaviours contained in the model.  
<br>

**Initial conditions**

With a valid SORTIE parameter file, the next step to initiation is to define the starting conditions for any one particular forest: run length, plot dimension, and starting forest composition.

For initial stand conditions, SORTIE is most often initiated by a tree list: a table that contains the density (stems/ha) of each tree species in user-defined diameter classes. Alternatively, a stand can be initiated through a spatial tree map (stem map) of the exact starting location, identity and size (diameter) of trees.

**SORTIE outputs**

There are many possible outputs from a SORTIE simulation. All the output options must be selected during the initiation and applied to the parameter file, including the desired location of the output file(s). There are two output files created during a SORTIE run: detailed and summary, with different options to select in either. 


## rsortie

`rsortie` is designed to support a continuous workflow from data management through to model outputs, making model development, parameterization, experimentation, and validation efficient and reproducible (McIntire et al. 2021 preprint).  

`rsortie` takes advantage of packages already developed in R, including the ability to manipulate datasets and spatial files effectively, supporting larger and more complex experiments applied within SORTIE.

Examples and uses of `rsortie` are explored in other vignettes.

`rsortie` can be used in a continuous workflow or in stages. *It is important to note that development of an `rsortie` workflow requires the use of the SORTIE GUI to set up the starting point.* Often with complex silviculture prescriptions or experimental designs, there may still be some stopping points within the workflow where a user *needs to interact with SORTIE through the GUI as well.*  

Creating the first SORTIE parameter file that define a SORTIE run *must occur in the GUI* before those variables (or parameters) are available to change in R.  
<br>  

A typical workflow in `rsortie` may include:

1. Importing field plot data and using R to manipulate the data and generate SORTIE initial tree conditions (in R)  
2. Defining a base parameter file - selecting behaviours, tree species, diameter size classes, etc. (in the SORTIE GUI)  
3. Using `makeFiles()` to update/ replace values in the base parameter file with new values (e.g., initial tree stand conditions, number of time steps, or values from a certain behaviour in a parameterization experiment)  
4. Modify silvicultural treatments (e.g., harvest or planting) defined in the base parameter file (in `rsortie`)
5. Run the model for each parameter file of interest, either in serial or parallel processing (in `rsortie`)
6. Extract and parse model outputs (in the SORTIE GUI or `rsortie`)
7. Analyze outputs (in R)

Literature Cited:
McIntire E, Chubaty A, Cumming S, et al. PERFICT: a Re-imagined Foundation for Predictive Ecology. Authorea Preprints; 2021. DOI: 10.22541/au.163252535.52485317/v1


